######################################################################
# Automatically generated by qmake (3.0) Wed Mar 6 15:34:02 2013
#####################################################################

TEMPLATE = app
TARGET = QmlApp
INCLUDEPATH += .
QT += quick sensors gui_private

QMAKE_INFO_PLIST = Info.plist

SOURCES += main.cpp
RESOURCES += main.qml qt.png

HEADERS += \
    ioscamera.h

OBJECTIVE_SOURCES += \
    ioscamera.mm
