######################################################################
# Automatically generated by qmake (3.0) Wed Mar 6 15:34:02 2013
######################################################################

TEMPLATE = app
TARGET = QmlApp
INCLUDEPATH += .
QT += qml quick sensors
QTPLUGIN += qtsensors_ios
CONFIG += release

# Input
SOURCES += main.cpp
RESOURCES += main.qrc
OTHER_FILES += main.qml Snippet.qml


cache()
